language: node_js
node_js:
  - "8"

before_script:
  - rm -rf .vuepress/dist/

script:
  - yarn run build

after_script:
  - cd .vuepress/dist
  - git init
  - git add -A
  - git commit -m "Deploy"
  - git push -f "https://${GH_TOKEN}@github.com/OOAD-Project/DashBoard.git" master:gh-pages

branches:
  only:
    - master